name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install json-schema-for-humans

      - name: Build schema documentation and provide examples for all schema versions
        run: |
          mkdir build
          mkdir build/v1.0
          mkdir build/v1.1
          cp schema/v1.0/schema.json build/v1.0/
          cp schema/v1.1/schema.json build/v1.1/
          cp schema/v1.1/schema.json build/
          cp -r examples/v1.0/*/ build/v1.0/
          cp -r examples/v1.1/*/ build/v1.1/
          cp -r examples/v1.1/*/ build/
          generate-schema-doc schema/v1.0/schema.json build/v1.0/index.html
          generate-schema-doc schema/v1.1/schema.json build/v1.1/index.html
          generate-schema-doc schema/v1.1/schema.json build/index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - id: deployment
        uses: actions/deploy-pages@v4
